// source/frontend/src/views/Plan/PlanList.vue
<template>
  <div class="plan-list">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>项目计划管理</span>
          <el-button type="primary" :icon="Plus" @click="handleCreate">
            创建计划
          </el-button>
        </div>
      </template>

      <!-- 搜索栏 -->
      <div class="search-bar">
        <el-input
          v-model="searchText"
          placeholder="搜索计划名称或项目名称"
          clearable
          style="width: 250px"
          @input="handleSearch"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>
      </div>

      <!-- 数据表格 -->
      <el-table
        :data="filteredPlans"
        :loading="loading"
        border
        stripe
        style="width: 100%; margin-top: 20px"
      >
        <el-table-column prop="name" label="计划名称" min-width="200" />
        <el-table-column prop="projectName" label="所属项目" min-width="200" />
        <el-table-column label="计划日期" width="200">
          <template #default="{ row }">
            {{ formatDateRange(row.startDate, row.endDate) }}
          </template>
        </el-table-column>
        <el-table-column label="包含阶段" width="280">
          <template #default="{ row }">
            <el-tag
              v-for="stage in row.stages"
              :key="stage.stageKey"
              :type="getStageType(stage.stageKey)"
              size="small"
              style="margin-right: 4px"
            >
              {{ stage.stageName }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="taskCount" label="任务数" width="100" align="center">
          <template #default="{ row }">
            {{ row.totalTasks }}
          </template>
        </el-table-column>
        <el-table-column label="进度" width="150">
          <template #default="{ row }">
            <el-tooltip placement="top">
              <template #content>
                <div style="max-width: 250px">
                  <div style="font-weight: bold; margin-bottom: 8px;">进度计算说明</div>
                  <div>1. 阶段进度 = 该阶段所有任务进度的平均值</div>
                  <div>2. 整体进度 = 各阶段进度按权重加权平均</div>
                  <div style="margin-top: 8px; color: #909399;">权重配置见阶段配置中的阶段权重</div>
                </div>
              </template>
              <el-progress
                :percentage="row.overallProgress"
                :stroke-width="8"
                style="cursor: help"
              />
            </el-tooltip>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="220" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" :icon="View" @click="handleView(row)">
              查看
            </el-button>
            <el-button link type="primary" :icon="Edit" @click="handleEdit(row)">
              编辑
            </el-button>
            <el-popconfirm
              title="确认删除"
              confirm-button-text="确定"
              cancel-button-text="取消"
              @confirm="handleDelete(row)"
            >
              <template #reference>
                <el-button link type="danger" :icon="Delete">
                  删除
                </el-button>
              </template>
            </el-popconfirm>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 计划表单弹窗 -->
    <PlanFormDialog
      v-model="formDialogVisible"
      :plan="currentPlan"
      :project-id="selectedProjectId"
      @submit="handleFormSubmit"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Search, Plus, View, Edit, Delete } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { usePlanStore } from '@/stores/plan'
import { useProjectStore } from '@/stores/project'
import type { ProjectPlan } from '@/types/plan'
import PlanFormDialog from '@/components/Plan/PlanFormDialog.vue'
import { stageApi, type Stage } from '@/api/stage'

const router = useRouter()
const planStore = usePlanStore()
const projectStore = useProjectStore()

const loading = ref(false)
const searchText = ref('')
const plans = ref<ProjectPlan[]>([])
const formDialogVisible = ref(false)
const currentPlan = ref<ProjectPlan | null>(null)
const selectedProjectId = ref(0)

// 阶段数据
const allStages = ref<Stage[]>([])

// 加载阶段数据
async function loadStages() {
  try {
    const data = await stageApi.getAllStages()
    allStages.value = data
  } catch (error) {
    console.error('加载阶段失败:', error)
  }
}

// 过滤后的计划列表
const filteredPlans = computed(() => {
  if (!searchText.value) {
    return plans.value
  }
  const keyword = searchText.value.toLowerCase()
  return plans.value.filter(plan =>
    (plan.name?.toLowerCase().includes(keyword) ||
    plan.projectName?.toLowerCase().includes(keyword))
  )
})

// 搜索处理
function handleSearch() {
  // 搜索由 computed 自动处理
}

// 查看详情
function handleView(plan: ProjectPlan) {
  router.push(`/plan/${plan.projectId}`)
}

// 创建计划
function handleCreate() {
  currentPlan.value = null
  // 如果只有一个项目，自动选中
  if (projectStore.projectList.length === 1) {
    selectedProjectId.value = projectStore.projectList[0].id
  } else {
    selectedProjectId.value = 0
  }
  formDialogVisible.value = true
}

// 编辑计划
function handleEdit(plan: ProjectPlan) {
  currentPlan.value = plan
  selectedProjectId.value = plan.projectId
  formDialogVisible.value = true
}

// 删除计划
async function handleDelete(plan: ProjectPlan) {
  try {
    if (plan.id) {
      await planStore.deletePlan(plan.id)
      ElMessage.success('删除成功')
    } else {
      // 如果没有后端记录，直接从列表移除
      plans.value = plans.value.filter(p => p.projectId !== plan.projectId)
      ElMessage.success('删除成功')
    }
    await loadPlans()
  } catch (error: any) {
    ElMessage.error(error.message || '删除失败')
  }
}

// 提交表单
async function handleFormSubmit(data: any) {
  try {
    if (currentPlan.value?.id) {
      await planStore.updatePlan(currentPlan.value.id, data)
      ElMessage.success('更新成功')
    } else {
      await planStore.createPlan(data)
      ElMessage.success('创建成功')
    }
    formDialogVisible.value = false
    await loadPlans()
  } catch (error: any) {
    ElMessage.error(error.message || '操作失败')
  }
}

// 格式化日期范围
function formatDateRange(startDate?: string, endDate?: string): string {
  if (!startDate || !endDate) return '-'
  return `${startDate} ~ ${endDate}`
}

// 获取阶段标签类型
function getStageType(stageKey: string) {
  const stage = allStages.value.find(s => s.key === stageKey)
  // 根据 progressMode 返回类型
  return stage?.progressMode === 'by_task' ? 'primary' : 'success'
}

// 加载项目计划数据
async function loadPlans() {
  loading.value = true
  try {
    // 尝试从后端获取计划列表
    try {
      const planList = await planStore.fetchPlanList()
      plans.value = planList.map((plan: any) => {
        // 解析阶段配置
        let stages = []
        if (plan.stagesJson) {
          try {
            stages = JSON.parse(plan.stagesJson)
          } catch (e) {
            console.error('解析阶段配置失败:', e)
          }
        }
        // 如果没有阶段配置，使用默认阶段
        if (stages.length === 0) {
          stages = getImplementationStages().map(s => ({
            stageKey: s.stageKey,
            startDate: plan.startDate,
            endDate: plan.endDate
          }))
        }
        return {
          ...plan,
          stages: stages.map(s => ({
            stageKey: s.stageKey,
            stageName: getStageLabel(s.stageKey),
            color: getStageColor(s.stageKey)
          })),
          // 使用后端返回的摘要数据，与详情页计算逻辑一致
          totalTasks: plan.totalTasks ?? 0,
          overallProgress: plan.overallProgress ?? 0
        }
      })
    } catch (e) {
      // 如果后端接口失败，使用项目列表作为备选
      await projectStore.fetchProjectList()
      const projects = projectStore.projectList

      plans.value = projects.map(project => ({
        projectId: project.id,
        projectName: project.name,
        projectCode: project.code,
        name: `${project.name}实施计划`,
        startDate: project.startDate,
        endDate: project.endDate || project.plannedEndDate,
        stages: getImplementationStages().map(s => ({
          stageKey: s.stageKey,
          stageName: s.stageName,
          color: s.color
        })),
        tasks: [],
        totalTasks: 0,
        overallProgress: 0
      }))
    }
  } finally {
    loading.value = false
  }
}

// 获取实施阶段
function getImplementationStages() {
  return [
    { stageKey: 'preparation', stageName: '准备阶段', color: '#409EFF' },
    { stageKey: 'construction', stageName: '施工阶段', color: '#67C23A' },
    { stageKey: 'configuration', stageName: '配置阶段', color: '#E6A23C' },
    { stageKey: 'verification', stageName: '核对阶段', color: '#909399' }
  ]
}

// 获取阶段标签
function getStageLabel(stageKey: string): string {
  const stage = getImplementationStages().find(s => s.stageKey === stageKey)
  return stage?.stageName || stageKey
}

// 获取阶段颜色
function getStageColor(stageKey: string): string {
  const stage = allStages.value.find(s => s.key === stageKey)
  return stage?.color || '#409EFF'
}

onMounted(() => {
  loadPlans()
  loadStages()
})
</script>

<style scoped>
.plan-list {
  padding: 8px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.info-tip {
  margin-bottom: 16px;
  padding: 12px;
  background: #ecf5ff;
  border: 1px solid #d9ecff;
  border-radius: 4px;
  color: #409EFF;
  font-size: 14px;
}

.search-bar {
  margin-top: 16px;
}
</style>

// requirement/prototype/frontend/src/pages/Plan/PlanList.tsx
import React, { useState, useEffect } from 'react';
import { Card, Table, Tag, Button, Space, Input, Popconfirm, message } from 'antd';
import { SearchOutlined, PlusOutlined, EyeOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { useProjectStore } from '../../stores/projectStore';
import { mockProjects } from '../../services/mockData';
import { ProjectPlan, ProjectStage } from '../../types/project';
import type { ColumnsType } from 'antd/es/table';
import PlanFormModal from '../../components/Plan/PlanFormModal';

// 实施阶段标签映射
const STAGE_LABELS: Record<string, { label: string; color: string }> = {
  planning: { label: '准备阶段', color: 'blue' },
  construction: { label: '施工阶段', color: 'processing' },
  configuration: { label: '配置阶段', color: 'orange' },
  verification: { label: '核对阶段', color: 'purple' },
};

interface PlanRecord {
  key: string;
  id: string;
  projectId: string;
  name: string;
  projectName: string;
  description?: string;
  startDate: string;
  endDate: string;
  stages: ProjectStage[];
}

const PlanList: React.FC = () => {
  const navigate = useNavigate();
  const { projects, setProjects, projectPlans, getProjectPlan, createProjectPlan, updateProjectPlan, deleteProjectPlan } = useProjectStore();
  const [searchText, setSearchText] = useState('');
  const [planModalVisible, setPlanModalVisible] = useState(false);
  const [editingPlan, setEditingPlan] = useState<ProjectPlan | null>(null);

  // 初始化项目数据
  useEffect(() => {
    if (projects.length === 0) {
      setProjects(mockProjects);
    }
  }, []);

  // 处理编辑
  const handleEdit = (planId: string) => {
    const plan = getProjectPlan(planId);
    if (plan) {
      setEditingPlan(plan);
      setPlanModalVisible(true);
    }
  };

  // 处理删除
  const handleDelete = (planId: string) => {
    deleteProjectPlan(planId);
    message.success('删除成功');
  };

  // 处理计划表单提交
  const handlePlanSubmit = (data: any) => {
    if (editingPlan) {
      updateProjectPlan(editingPlan.id, data);
      message.success('更新成功');
    } else {
      createProjectPlan(data);
      message.success('创建成功');
    }
    setPlanModalVisible(false);
    setEditingPlan(null);
  };

  // 处理关闭计划表单
  const handlePlanModalClose = () => {
    setPlanModalVisible(false);
    setEditingPlan(null);
  };

  // 处理创建新计划
  const handleCreatePlan = () => {
    setEditingPlan(null);
    setPlanModalVisible(true);
  };

  // 过滤后的计划列表
  const filteredPlans = projectPlans
    .filter(p => {
      const project = projects.find(proj => proj.id === p.projectId);
      const matchSearch = !searchText ||
        p.name.toLowerCase().includes(searchText.toLowerCase()) ||
        (project && project.name.toLowerCase().includes(searchText.toLowerCase()));
      return matchSearch;
    })
    .map(p => {
      const project = projects.find(proj => proj.id === p.projectId);
      return {
        key: p.id,
        id: p.id,
        name: p.name,
        projectName: project?.name || '未知项目',
        description: p.description,
        startDate: p.startDate,
        endDate: p.endDate,
        stages: p.stages.map(s => s.stage),
        projectId: p.projectId,
      };
    });

  const columns: ColumnsType<PlanRecord> = [
    {
      title: '计划名称',
      dataIndex: 'name',
      key: 'name',
      width: 200,
      ellipsis: true,
    },
    {
      title: '所属项目',
      dataIndex: 'projectName',
      key: 'projectName',
      width: 200,
      ellipsis: true,
    },
    {
      title: '包含阶段',
      dataIndex: 'stages',
      key: 'stages',
      width: 240,
      render: (stages: ProjectStage[]) => (
        <Space size="small" wrap>
          {stages.map(stage => {
            const { label, color } = STAGE_LABELS[stage] || { label: stage, color: 'default' };
            return <Tag key={stage} color={color}>{label}</Tag>;
          })}
        </Space>
      ),
    },
    {
      title: '计划开始日期',
      dataIndex: 'startDate',
      key: 'startDate',
      width: 120,
    },
    {
      title: '计划结束日期',
      dataIndex: 'endDate',
      key: 'endDate',
      width: 120,
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      fixed: 'right' as const,
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EyeOutlined />}
            onClick={() => navigate(`/plan/${record.projectId}`)}
          >
            查看
          </Button>
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record.id)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确认删除"
            description="确定要删除这个计划吗？"
            onConfirm={() => handleDelete(record.id)}
            okText="确定"
            cancelText="取消"
          >
            <Button
              type="link"
              size="small"
              icon={<DeleteOutlined />}
              danger
            >
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Card
        title={
          <Space>
            <span>项目计划管理</span>
          </Space>
        }
        extra={
          <Space>
            <Input
              placeholder="搜索计划名称或项目名称"
              prefix={<SearchOutlined />}
              style={{ width: 250 }}
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              allowClear
            />
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={handleCreatePlan}
            >
              创建计划
            </Button>
          </Space>
        }
      >
        <div style={{ marginBottom: 16, color: '#666', fontSize: 14 }}>
          项目计划仅针对实施阶段（准备/施工/配置/核对），用于管理项目的实施计划和任务安排。
        </div>

        <Table
          columns={columns}
          dataSource={filteredPlans}
          pagination={{
            total: filteredPlans.length,
            pageSize: 10,
            showSizeChanger: true,
            showTotal: (total) => `共 ${total} 个计划`,
          }}
          scroll={{ x: 1000 }}
        />
      </Card>

      {/* 计划表单 Modal */}
      {planModalVisible && (
        <PlanFormModal
          visible={planModalVisible}
          plan={editingPlan}
          projectId={editingPlan?.projectId || projects[0]?.id || ''}
          onClose={handlePlanModalClose}
          onSubmit={handlePlanSubmit}
        />
      )}
    </div>
  );
};

export default PlanList;
